Repository newrelic/nri-kubernetes, pull requests merged in 2023-08, with the labels that each got.

#836 chore: Update CHANGELOG format
  CHANGELOG.md
  CONTRIBUTING.md
Labels: ci/skip-e2e

#837 chore: Add CHANGELOG github workflow
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: ci/skip-e2e, Skip Changelog

#843 Chore: Update changelog workflow
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: ci/skip-e2e

#840 chore: Add Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: ci/skip-e2e, ci/skip-load-test

#847 chore: Add labels to changelog workflow and renovatebot
  .github/renovate.json5
  .github/workflows/changelog.yml
  CONTRIBUTING.md
Labels: ci/skip-e2e, ci/skip-load-test, Skip Changelog

#856 Update CHANGELOG
  CHANGELOG.md
Labels: ci/skip-e2e, Skip Changelog

#857 Bump versions
  charts/newrelic-infrastructure/Chart.yaml
Labels: ci/skip-e2e, Skip Changelog
